/*Create a class named as AccConAndOppOperations and Write methods for each of the following requirements:
PART 1 – SOQL In Apex
1. Write the logic to fetch and return all the accounts. Include account name, annual revenue, type, and source of account.
2. Prepare a method which will return the List of Accounts (fetch any 3 fields) for a particular Type. Type should be sent as a parameter in the method.
3. Print all the opportunities (fetch Amount, Name and Account Name fields) with Stage as 'Closed Won' and make it dynamic so that it should work for other stages as well.
4. Find all the opportunities which has Lead Source as 'Web' and Stage as 'Closed Lost'. Make it dynamic so that it works for other stages and Lead sources as well.
5. Prepare a method which returns the sum of all the opportunities Amount present in the org.
6. Prepare a method which will return all the Accounts for which at least a closed Won Opportunity is present. Make it dynamic if we want to bring account for other opportunity stageNames.
7. Print the Annual revenue and name of all the accounts of type 'Customer - Direct' and print the Opportunity Name and Amount for the respective 'Closed Won' opportunities. Printing should be done one by one in different lines.
8. Prepare a method which will return all the Accounts for which at least a contact is present*/

public  class AccConAndOppOperations {
    public 

    
}
