public class Ali {
    public void metot() {

            string  name = 'ali';
            integer yas  = 11;
            Object  obj1 = 'USA';
            long    uzun = 1234567890;
            boolean acaba = true;


            system.debug(name);
            system.debug('benim oglumun ismi ' + name);
            system.debug('oglumun yasi' + yas );
            system.debug(obj1);
            system.debug(uzun);
            system.debug('okul acik mi? ' + acaba);



       }
    }



    