public class Calculator {
   /* public void dynamicCalculatorMethod(Decimal pr1, decimal pr2,string operator){
     if (operator=='ADDITION') {
         
     } else {
         
     }   
    }
    //---> access modifier
    

    public c void welcomeMessage() {
        system.debug('Welcome to apex calc.');
    }

    public void printNewMessage(string msg) {
        system.debug(msg);
    }*/

    public  static integer method_add(integer a, Integer b) {
        Integer sum = a + b ;
         //  System.debug('sum   =' + sum);
         return sum; 
        }

    
   /* public integer method_sub(integer a, Integer b) {
            Integer subt = a - b ;
             //  System.debug('sum   =' + sum);
             return subt; 
         }
    
     public integer method_add(integer a, integer b, integer c) {
        integer d = a+b+c ;
        return d;
     }   */
    
   /* public decimal dynamicCalculation(decimal a, decimal b, string s) {
        decimal result;
        if(s == 'addition') {
            result = a + b;}
        else if(s == 'subtraction') {
            result = a-b;}
        else if(s == 'division') {
            result = a/b;}       
        else if(s== 'multi'){
             result = a*b;}
        
             return result; }*/

        }


    
