public class Candidates {
    public string Name;
    public string Gender;
    public static string CompanyName;


    public void printCandidates() {
        System.debug('Candidate name is    ' + Name + ' ( ' + Gender + ' )');
        System.debug('Company Name is  '+ CompanyName);
    }

  public static  void printCandidateInfo(){
      system.debug('Company name '+ CompanyName);
      
  }










}
