public class MyIntroduction {
    public void printMyIntroduction() {

        string name = 'Melike';
        system.debug('My name is ' +name);


        string city = 'I live in Houston';
        system.debug(city);

        Object obj1 = 'I like reading';
        system.debug(obj1);

        boolean isItBackground = false;
        system.debug('My IT Background = ' + isItBackground);

        integer totalBook = 30;
        system.debug('I read '+totalBook +' books per year');

        long phoneNumber = 71322555;
        system.debug('my number is   : ' + phoneNumber);

    

    }
}
