
Candidates.CompanyName = 'Soft Inovas';

Candidates c1 = new Candidates();
c1.Name = 'Ali';
c1.Gender = 'Male';
c1.printCandidates();

Candidates c2 = new Candidates();
c2.Name = 'Ayse';
c2.Gender = 'Female';
c2.printCandidates();

Candidates.CompanyName = 'Soft Inovas-22';
Candidates c3 = new Candidates();
c3.Name = 'Ahmet';
c3.Gender = 'Male';
c3.printCandidates();

Candidates.printCandidateInfo();