/*Planet earth = new Planet();
earth.planetName ='Earth';
earth.planetNumber= 3;
earth.numberOfMoons=1;
system.debug('Earth'    + earth);
Planet venus = new Planet();
venus.planetName = 'Venus';
venus.planetNumber = 4;
venus.numberOfMoons =1;
system.debug('Venus'   + venus);
Planet mars = new Planet();
mars.planetName = 'Mars';
mars.planetNumber = 4;
mars.numberOfMoons =1;
system.debug('Mars'   + mars);*/

string a = ListPractise.addPlanet('',3,2);
system.debug('your planets message' +a);